site_name: "Arena-Electron"
site_url: http://crnlpanic.github.io/Arena-Electron
repo_name: 'crnlPanic/Arena-Electron'
repo_url: 'https://github.com/crnlPanic/Arena-Electron/'
pages:
  - Home: "index.md"
  - Game:
    - Arena: "game/arena.md"
    - Bullet: "game/bullet.md"
    - Obstacle: "game/obstacle.md"
    - Player: "game/player.md"
  - About:
    - Changelog: "about/changes.md"
    - Contribution Guide: "about/contrib.md"
    - License: "about/license.md"
theme: material
markdown_extensions:
  - admonition
  - codehilite
  - toc(permalink=true)
extra:
  palette:
    primary: 'blue grey'
    accent: 'red'
  font:
    code: 'Ubuntu Mono'
  social:
    - type: 'twitter'
      link: 'https://twitter.com/crnbrdrck'
    - type: 'wordpress'
      link: 'https://crnlpanic.wordpress.com'

